#!/usr/bin/env bash
# Installer for matthewcode.
# Sets up the conda env and drops a launcher onto PATH so `matthewcode`
# is runnable from any directory. The launcher activates the conda env
# in its own subshell, so the user's parent shell is never modified.
#
# Usage:
#   bash install.sh                 # install to ~/.local/bin
#   bash install.sh --prefix DIR    # install launcher to DIR instead
#   bash install.sh --update        # also run `conda env update --prune`
#   bash install.sh --help

set -euo pipefail

PREFIX="$HOME/.local/bin"
DO_UPDATE=0
ENV_NAME="matthewcode"

usage() {
    cat <<EOF
Usage: bash install.sh [--prefix DIR] [--update] [--help]

  --prefix DIR   Install the launcher into DIR (default: \$HOME/.local/bin).
  --update       Run 'conda env update --prune' even if the env exists.
  --help         Show this message.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)
            [ $# -ge 2 ] || { echo "error: --prefix needs a directory" >&2; exit 2; }
            PREFIX="$2"
            shift 2
            ;;
        --prefix=*)
            PREFIX="${1#--prefix=}"
            shift
            ;;
        --update)
            DO_UPDATE=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "error: unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

# Resolve the absolute path to this repo (the directory containing install.sh).
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f "$REPO_DIR/matthewcode.py" ]; then
    echo "error: matthewcode.py not found next to install.sh (looked in $REPO_DIR)" >&2
    exit 1
fi
if [ ! -f "$REPO_DIR/environment.yml" ]; then
    echo "error: environment.yml not found in $REPO_DIR" >&2
    exit 1
fi

# 1. Locate conda.
find_conda() {
    if command -v conda >/dev/null 2>&1; then
        command -v conda
        return 0
    fi
    for candidate in \
        "${CONDA_EXE:-}" \
        "$HOME/miniconda3/bin/conda" \
        "$HOME/anaconda3/bin/conda" \
        "$HOME/miniforge3/bin/conda" \
        "$HOME/mambaforge/bin/conda" \
        "/opt/homebrew/anaconda3/bin/conda" \
        "/opt/conda/bin/conda" \
        "/opt/miniconda3/bin/conda" \
        "/usr/local/miniconda3/bin/conda" \
        "/usr/local/anaconda3/bin/conda"
    do
        if [ -n "$candidate" ] && [ -x "$candidate" ]; then
            echo "$candidate"
            return 0
        fi
    done
    return 1
}

if ! CONDA_BIN="$(find_conda)"; then
    cat >&2 <<EOF
error: conda not found.

Install miniforge (recommended) or miniconda first:
  - https://github.com/conda-forge/miniforge
  - https://docs.conda.io/en/latest/miniconda.html

Then re-run: bash install.sh
EOF
    exit 1
fi

CONDA_BASE="$("$CONDA_BIN" info --base)"
if [ -z "$CONDA_BASE" ] || [ ! -f "$CONDA_BASE/etc/profile.d/conda.sh" ]; then
    echo "error: could not locate conda.sh under $CONDA_BASE/etc/profile.d/" >&2
    exit 1
fi

echo "==> using conda at $CONDA_BIN (base: $CONDA_BASE)"

# 2. Create or update the env.
# `conda env list` prints one env per line; the env name is the first whitespace-separated token.
env_exists() {
    "$CONDA_BIN" env list | awk '{print $1}' | grep -Fxq "$ENV_NAME"
}

if env_exists; then
    if [ "$DO_UPDATE" -eq 1 ]; then
        echo "==> updating env '$ENV_NAME' from environment.yml"
        "$CONDA_BIN" env update -n "$ENV_NAME" -f "$REPO_DIR/environment.yml" --prune
    else
        echo "==> env '$ENV_NAME' already exists, skipping (re-run with --update to refresh)"
    fi
else
    echo "==> creating env '$ENV_NAME' from environment.yml"
    "$CONDA_BIN" env create -f "$REPO_DIR/environment.yml"
fi

# 3. Prepare the install prefix.
mkdir -p "$PREFIX"
LAUNCHER="$PREFIX/matthewcode"

# 4. Write the launcher. It activates the env in its own subshell and execs python,
#    so exiting matthewcode automatically tears the env down — the parent shell
#    never had it active.
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by matthewcode/install.sh — do not edit by hand.
# Re-run install.sh to regenerate.
set -e

REPO_DIR="$REPO_DIR"
CONDA_BASE="$CONDA_BASE"
ENV_NAME="$ENV_NAME"

# shellcheck disable=SC1091
. "\$CONDA_BASE/etc/profile.d/conda.sh"
conda activate "\$ENV_NAME"

exec python "\$REPO_DIR/matthewcode.py" "\$@"
EOF
chmod +x "$LAUNCHER"

echo "==> wrote launcher to $LAUNCHER"

# 5. PATH check.
case ":$PATH:" in
    *":$PREFIX:"*)
        ON_PATH=1
        ;;
    *)
        ON_PATH=0
        ;;
esac

if [ "$ON_PATH" -ne 1 ]; then
    echo
    echo "note: $PREFIX is not on your PATH."
    if [ "$(uname -s)" = "Darwin" ]; then
        rc_hint="~/.zshrc (or ~/.bash_profile)"
    else
        rc_hint="~/.bashrc (or ~/.zshrc)"
    fi
    echo "      Add this line to $rc_hint and open a new shell:"
    echo
    echo "          export PATH=\"$PREFIX:\$PATH\""
    echo
fi

# 6. Summary.
cat <<EOF
==> done.

  repo:     $REPO_DIR
  conda:    $CONDA_BASE
  env:      $ENV_NAME
  launcher: $LAUNCHER

Try it:  matthewcode --help
EOF
